python: can't open file '/www/wwwroot/wurenzhibo/run.py': [Errno 2] No such file or directory
[2023-12-22 21:17:29 +0800] [1351871] [INFO] Starting gunicorn 21.2.0
[2023-12-22 21:17:29 +0800] [1351871] [INFO] Listening at: http://0.0.0.0:5016 (1351871)
[2023-12-22 21:17:29 +0800] [1351871] [INFO] Using worker: sync
[2023-12-22 21:17:29 +0800] [1351873] [INFO] Booting worker with pid: 1351873
[2023-12-22 21:17:29 +0800] [1351873] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/anaconda3/envs/bertVits/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/root/anaconda3/envs/bertVits/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/anaconda3/envs/bertVits/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/anaconda3/envs/bertVits/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/anaconda3/envs/bertVits/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/anaconda3/envs/bertVits/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/anaconda3/envs/bertVits/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/root/anaconda3/envs/bertVits/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'infer'
[2023-12-22 21:17:29 +0800] [1351873] [INFO] Worker exiting (pid: 1351873)
[2023-12-22 21:17:29 +0800] [1351871] [ERROR] Worker (pid:1351873) exited with code 3
[2023-12-22 21:17:29 +0800] [1351871] [ERROR] Shutting down: Master
[2023-12-22 21:17:29 +0800] [1351871] [ERROR] Reason: Worker failed to boot.
